### PR TITLE
added extra_combos field to etl.pad.storage.monster.py

### PR DESCRIPTION
**Pull request by hhxhhxhhx**
…ill_info.py

added max_combos field in LeaderSkill in etl/pad/storage/monster.py

### CODE REVIEW

**Comment by nachoapps** [comment]
For this to work, there also needs to be a database change. Can you comment the SQL used into the PR?

**Comment by hhxhhxhhx** [comment]
i'm guessing this is schema/mysql.sql? also what does PR stand for lmao

**Comment by nachoapps** [comment]
schema/mysql.sql isn't actually used for anything, it's just a static dump of the database. See https://github.com/nachoapps/dadguide-data/tree/master/schema#regenerating-the-schema-dump for details.

Did you test this change? If so, you must have run a SQL command that looks like
`alter table leader_skills add column extra_combos int default 0` (just typed off the top of my head, might not be correct). Otherwise the data loader would not work. I'm asking for the SQL you ran to adjust the database in order to receive this new field.

**Comment by nachoapps** [comment]
Oops, also FYI 'PR' is short for 'Pull Request', the thing we're doing right now :)

**Pull request closed without merging**
